export enum LogRedirectionStrategy {
  ALWAYS_PRINT_LOGS = 1,
  PRINT_LOGS_WHEN_NO_CALLBACKS_DEFINED = 2,
  PRINT_LOGS_WHEN_GLOBAL_CALLBACK_NOT_DEFINED = 3,
  PRINT_LOGS_WHEN_SESSION_CALLBACK_NOT_DEFINED = 4,
  NEVER_PRINT_LOGS = 5
}
