name: custom android build scripts

on: [ push, pull_request ]

jobs:
  build-main-on-linux:
    name: android main on linux
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ndk-version: [ 'r23-linux' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: set up adopt jdk 8
        uses: actions/setup-java@v2.2.0
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: set up android ndk
        run: |
          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
          unzip -q -o ndk.zip -d .ndk
          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
      - name: run the build script
        run: ./android.sh --api-level=21 --enable-android-media-codec --enable-android-zlib --no-archive --disable-arm-v7a --disable-x86
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
      - name: print ffbuild logs
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'

      - uses: actions/upload-artifact@v2
        with:
          name: build-main-on-linux
          path: ${{runner.workspace}}/ffmpeg-kit/prebuilt/

  build-lts-on-linux:
    name: android lts on linux
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ndk-version: [ 'r23-linux' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: set up adopt jdk 8
        uses: actions/setup-java@v2.2.0
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: set up android ndk
        run: |
          curl -s "https://dl.google.com/android/repository/android-ndk-${{ matrix.ndk-version }}.zip" -o ndk.zip
          unzip -q -o ndk.zip -d .ndk
          echo "ANDROID_NDK_ROOT=$PWD/.ndk/$(ls .ndk)" >> $GITHUB_ENV
      - name: run the build script
        run: ./android.sh --lts --api-level=21 --enable-android-media-codec --enable-android-zlib --no-archive --disable-arm-v7a --disable-x86
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
      - name: print ffbuild logs
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'

      - uses: actions/upload-artifact@v2
        with:
          name: build-lts-on-linux
          path: ${{runner.workspace}}/ffmpeg-kit/prebuilt/
